### ISSUE TITLE
Crash Report: Crash after freeze one address and changing another

### ISSUE THREAD

**Issue by kdecks** [GameDragon2k/RASuite#13]
DLL: 0.069
Emulator: RANes 0.013
Game: Castlevania: The holy Relic

After freezing any address and attempting to change any other address the emulator will crash. You can make changes to the frozen address. Tested 6 times.

**Comment by kdecks** [comment]
Unfreezing and then attempting to make a change will still result in a crash.

**Comment by GameDragon2k** [comment]
The crash happens when the bookmark window is opened period. Doesn't have anything to do with freezing values.

**Comment by GameDragon2k** [comment]
Should be resolved now.
