### ISSUE TITLE
RAP64 0.57 crashing while saving a bookmark of a large note

### ISSUE THREAD

**Issue by kdecks** [GameDragon2k/RASuite#3]
Example:
0x16e0a4 for Star Fox 64 v1.0

Tested 3 times. Did not test other notes.

Intermediate bug.

**Comment by GameDragon2k** [comment]
Fixed. Doubled limit from 256 characters to 512.

![image](https://user-images.githubusercontent.com/3225327/36086750-1429b73e-0f9c-11e8-8762-7de43016679d.png)
