### ISSUE TITLE
Processing Active Button visual not shared between Active Achievement Groups

### ISSUE THREAD

**Issue by kdecks** [GameDragon2k/RASuite#4]
In the achievements window, 

Example: If I'm in core Achievements with "Processing Active" unchecked, and then go to Local the "Processing Active" checkmark will appear unchecked even though processing is active in Local.

Each group still has it's own avctive or inactive state, but the checkmark is not reflecting this state.
Also the checkmark will invert the current state, not go to the correct visual, after selected.

**Comment by GameDragon2k** [comment]
Fixed. This was likely an issue that existed for months, but I never noticed it.
