### ISSUE TITLE
Leaderboard submits work in softcore

### ISSUE THREAD

**Issue by kdecks** [GameDragon2k/RASuite#7]
There are too many ways to abuse this to get unfair scores.

I think it's ideal to leave enough for debugging, but no true score submissions.

**Comment by GameDragon2k** [comment]
Will take a bit of time to make some adjustments for this to work.

**Comment by GameDragon2k** [comment]
Forgot to close this.

Added several options to display/hide leaderboard popups and allow development in softcore mode.
