### ISSUE TITLE
After local achievements are saved the text remains red

### ISSUE THREAD

**Issue by kdecks** [GameDragon2k/RASuite#9]
They should turn black after being saved.

They stay red until the achievements are reloaded.

minor issue.

**Comment by kdecks** [comment]
In addition, after saving in local while attempting to load another file you'll get this popup:

![image](https://user-images.githubusercontent.com/32706333/36001120-7dff50ae-0ce2-11e8-8b51-5d3d1dfdbaf8.png)

**Comment by GameDragon2k** [comment]
Fixed. Thank you.
